# Generated by Django 4.1.7 on 2023-04-08 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(max_length=6, primary_key=True, serialize=False, unique=True, verbose_name='ID'),
        ),
    ]
