# Generated by Django 4.1.7 on 2023-04-08 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0002_alter_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='userCred',
            fields=[
                ('reg', models.CharField(default='', max_length=15, primary_key=True, serialize=False)),
                ('dob', models.DateField(verbose_name='DOB')),
                ('course', models.CharField(max_length=15)),
                ('branch', models.CharField(default='', max_length=15)),
                ('hosteller', models.BooleanField(default=True)),
                ('blockName', models.CharField(default='', max_length=15)),
                ('roomno', models.CharField(default='', max_length=15)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='cred',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth_api.usercred'),
        ),
    ]
