# Generated by Django 4.1.7 on 2023-04-11 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0003_usercred_user_cred'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercred',
            name='sem',
            field=models.CharField(default='', max_length=5),
        ),
    ]
