# Generated by Django 4.2 on 2023-04-29 14:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0004_usercred_sem'),
    ]

    operations = [
        migrations.CreateModel(
            name='security',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outinstance', models.DateTimeField(auto_now=True)),
                ('ininstance', models.DateTimeField()),
                ('stu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
