# Generated by Django 4.2 on 2023-04-30 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0005_security'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='security',
            new_name='LocalOuting',
        ),
    ]
