# Generated by Django 4.2 on 2023-04-30 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0007_nonlocalouting'),
    ]

    operations = [
        migrations.AddField(
            model_name='localouting',
            name='security_ispermitted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='nonlocalouting',
            name='security_ispermitted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='nonlocalouting',
            name='warden_ispermitted',
            field=models.BooleanField(default=False),
        ),
    ]
