# Generated by Django 4.2 on 2023-04-30 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0009_alter_localouting_ininstance'),
    ]

    operations = [
        migrations.AddField(
            model_name='localouting',
            name='outdate',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='localouting',
            name='ininstance',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='localouting',
            name='outinstance',
            field=models.TimeField(auto_now=True),
        ),
    ]
