# Generated by Django 4.2 on 2023-05-01 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0010_localouting_outdate_alter_localouting_ininstance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nonlocalouting',
            name='modeoft',
            field=models.CharField(default='', max_length=20),
        ),
    ]
