# Generated by Django 4.2 on 2023-05-01 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0011_nonlocalouting_modeoft'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nonlocalouting',
            name='ininstance',
            field=models.DateTimeField(null=True),
        ),
    ]
