# Generated by Django 4.2 on 2023-05-01 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0012_alter_nonlocalouting_ininstance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localouting',
            name='ininstance',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nonlocalouting',
            name='ininstance',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
