# Generated by Django 4.2 on 2023-05-02 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0015_alter_localouting_id_alter_nonlocalouting_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercred',
            name='credits',
            field=models.IntegerField(default=32500, null=True),
        ),
    ]
