# Generated by Django 4.2 on 2023-05-03 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0017_nonlocalouting_return_permitted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nonlocalouting',
            old_name='return_permitted',
            new_name='return_ispermitted',
        ),
    ]
